In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/vancouver_crime_all.csv')

crime.head(20)

,c_id,type,datetime,year,month,day,hour,minute,Hour_Minute,hundred_block,...,signal_200,trees_25,trees_100,rain_mm,snow_cm,total_precip_mm,temp_c,humidity,pressure,hours_of_light
0,16,Theft of Bicycle,2003-01-01 00:00:00,2003,1,1,0,5,0.083333,11XX HORNBY ST,...,9,7,55,21.6,0.0,21.6,5.8,81.0,101.7,9.53
1,10,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,33XX ROSEMONT DR,...,0,14,62,21.6,0.0,21.6,5.8,81.0,101.7,9.53
2,15,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,1,0.016667,26XX E 48TH AVE,...,2,8,38,21.6,0.0,21.6,5.8,81.0,101.7,9.53
3,18,Break and Enter Residential/Other,2003-01-01 00:00:00,2003,1,1,0,20,0.333333,19XX PARKER ST,...,1,8,88,21.6,0.0,21.6,5.8,81.0,101.7,9.53
4,5,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,X NK_LOC ST,...,13,6,39,21.6,0.0,21.6,5.8,81.0,101.7,9.53
5,6,Mischief,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,17XX PARKER ST,...,3,7,58,21.6,0.0,21.6,5.8,81.0,101.7,9.53
6,17,Vehicle Collision or Pedestrian Struck (with I...,2003-01-01 00:00:00,2003,1,1,0,19,0.316667,NELSON ST / THURLOW ST,...,5,5,46,21.6,0.0,21.6,5.8,81.0,101.7,9.53
7,21,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,30,0.500000,4XX ABBOTT ST,...,7,5,55,21.6,0.0,21.6,5.8,81.0,101.7,9.53
8,3,Break and Enter Residential/Other,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,9XX W 15TH AVE,...,2,0,32,21.6,0.0,21.6,5.8,81.0,101.7,9.53
9,1,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,57XX CULLODEN ST,...,2,6,49,21.6,0.0,21.6,5.8,81.0,101.7,9.53
10,9,Break and Enter Commercial,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,64XX VICTORIA DR,...,2,5,40,21.6,0.0,21.6,5.8,81.0,101.7,9.53
11,7,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,11XX HOWE ST,...,9,3,78,21.6,0.0,21.6,5.8,81.0,101.7,9.53
12,14,Break and Enter Residential/Other,2003-01-01 00:00:00,2003,1,1,0,1,0.016667,34XX W 42ND AVE,...,3,6,38,21.6,0.0,21.6,5.8,81.0,101.7,9.53
13,13,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,1,0.016667,X NK_LOC ST,...,13,6,39,21.6,0.0,21.6,5.8,81.0,101.7,9.53
14,11,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,2XX DRAKE ST,...,7,13,62,21.6,0.0,21.6,5.8,81.0,101.7,9.53
15,20,Mischief,2003-01-01 00:00:00,2003,1,1,0,30,0.500000,15XX W 66TH AVE,...,4,7,59,21.6,0.0,21.6,5.8,81.0,101.7,9.53
16,8,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,10XX W 26TH AVE,...,1,5,31,21.6,0.0,21.6,5.8,81.0,101.7,9.53
17,2,Theft of Bicycle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,6X KEEFER PL,...,6,8,49,21.6,0.0,21.6,5.8,81.0,101.7,9.53
18,19,Mischief,2003-01-01 00:00:00,2003,1,1,0,30,0.500000,9XX CANADA PL,...,6,0,22,21.6,0.0,21.6,5.8,81.0,101.7,9.53
19,12,Theft from Vehicle,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,24XX W 1ST AVE,...,1,10,74,21.6,0.0,21.6,5.8,81.0,101.7,9.53

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['Mischief', 'Theft from Vehicle',
       'Vehicle Collision or Pedestrian Struck (with Injury)',
       'Theft of Vehicle', 'Theft of Bicycle', 'Other Theft',
       'Vehicle Collision or Pedestrian Struck (with Fatality)'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head(20)

,c_id,type,datetime,year,month,day,hour,minute,Hour_Minute,hundred_block,...,signal_200,trees_25,trees_100,rain_mm,snow_cm,total_precip_mm,temp_c,humidity,pressure,hours_of_light
0,16,0,2003-01-01 00:00:00,2003,1,1,0,5,0.083333,11XX HORNBY ST,...,9,7,55,21.6,0.0,21.6,5.8,81.0,101.7,9.53
1,10,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,33XX ROSEMONT DR,...,0,14,62,21.6,0.0,21.6,5.8,81.0,101.7,9.53
2,15,0,2003-01-01 00:00:00,2003,1,1,0,1,0.016667,26XX E 48TH AVE,...,2,8,38,21.6,0.0,21.6,5.8,81.0,101.7,9.53
3,18,1,2003-01-01 00:00:00,2003,1,1,0,20,0.333333,19XX PARKER ST,...,1,8,88,21.6,0.0,21.6,5.8,81.0,101.7,9.53
4,5,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,X NK_LOC ST,...,13,6,39,21.6,0.0,21.6,5.8,81.0,101.7,9.53
5,6,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,17XX PARKER ST,...,3,7,58,21.6,0.0,21.6,5.8,81.0,101.7,9.53
6,17,0,2003-01-01 00:00:00,2003,1,1,0,19,0.316667,NELSON ST / THURLOW ST,...,5,5,46,21.6,0.0,21.6,5.8,81.0,101.7,9.53
7,21,0,2003-01-01 00:00:00,2003,1,1,0,30,0.500000,4XX ABBOTT ST,...,7,5,55,21.6,0.0,21.6,5.8,81.0,101.7,9.53
8,3,1,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,9XX W 15TH AVE,...,2,0,32,21.6,0.0,21.6,5.8,81.0,101.7,9.53
9,1,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,57XX CULLODEN ST,...,2,6,49,21.6,0.0,21.6,5.8,81.0,101.7,9.53
10,9,1,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,64XX VICTORIA DR,...,2,5,40,21.6,0.0,21.6,5.8,81.0,101.7,9.53
11,7,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,11XX HOWE ST,...,9,3,78,21.6,0.0,21.6,5.8,81.0,101.7,9.53
12,14,1,2003-01-01 00:00:00,2003,1,1,0,1,0.016667,34XX W 42ND AVE,...,3,6,38,21.6,0.0,21.6,5.8,81.0,101.7,9.53
13,13,0,2003-01-01 00:00:00,2003,1,1,0,1,0.016667,X NK_LOC ST,...,13,6,39,21.6,0.0,21.6,5.8,81.0,101.7,9.53
14,11,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,2XX DRAKE ST,...,7,13,62,21.6,0.0,21.6,5.8,81.0,101.7,9.53
15,20,0,2003-01-01 00:00:00,2003,1,1,0,30,0.500000,15XX W 66TH AVE,...,4,7,59,21.6,0.0,21.6,5.8,81.0,101.7,9.53
16,8,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,10XX W 26TH AVE,...,1,5,31,21.6,0.0,21.6,5.8,81.0,101.7,9.53
17,2,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,6X KEEFER PL,...,6,8,49,21.6,0.0,21.6,5.8,81.0,101.7,9.53
18,19,0,2003-01-01 00:00:00,2003,1,1,0,30,0.500000,9XX CANADA PL,...,6,0,22,21.6,0.0,21.6,5.8,81.0,101.7,9.53
19,12,0,2003-01-01 00:00:00,2003,1,1,0,0,0.000000,24XX W 1ST AVE,...,1,10,74,21.6,0.0,21.6,5.8,81.0,101.7,9.53

In [3]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))
crime['neighbourhood'] = le.fit_transform(crime['neighbourhood'].astype(str))



# Display the results
crime.head(20)

,c_id,type,datetime,year,month,day,hour,minute,Hour_Minute,hundred_block,...,signal_200,trees_25,trees_100,rain_mm,snow_cm,total_precip_mm,temp_c,humidity,pressure,hours_of_light
0,16,0,0,2003,1,1,0,5,0.083333,480,...,9,7,55,21.6,0.0,21.6,5.8,81.0,101.7,9.53
1,10,0,0,2003,1,1,0,0,0.000000,6995,...,0,14,62,21.6,0.0,21.6,5.8,81.0,101.7,9.53
2,15,0,0,2003,1,1,0,1,0.016667,4876,...,2,8,38,21.6,0.0,21.6,5.8,81.0,101.7,9.53
3,18,1,0,2003,1,1,0,20,0.333333,2687,...,1,8,88,21.6,0.0,21.6,5.8,81.0,101.7,9.53
4,5,0,0,2003,1,1,0,0,0.000000,21898,...,13,6,39,21.6,0.0,21.6,5.8,81.0,101.7,9.53
5,6,0,0,2003,1,1,0,0,0.000000,2172,...,3,7,58,21.6,0.0,21.6,5.8,81.0,101.7,9.53
6,17,0,0,2003,1,1,0,19,0.316667,19644,...,5,5,46,21.6,0.0,21.6,5.8,81.0,101.7,9.53
7,21,0,0,2003,1,1,0,30,0.500000,9726,...,7,5,55,21.6,0.0,21.6,5.8,81.0,101.7,9.53
8,3,1,0,2003,1,1,0,0,0.000000,14807,...,2,0,32,21.6,0.0,21.6,5.8,81.0,101.7,9.53
9,1,0,0,2003,1,1,0,0,0.000000,10688,...,2,6,49,21.6,0.0,21.6,5.8,81.0,101.7,9.53
10,9,1,0,2003,1,1,0,0,0.000000,11852,...,2,5,40,21.6,0.0,21.6,5.8,81.0,101.7,9.53
11,7,0,0,2003,1,1,0,0,0.000000,481,...,9,3,78,21.6,0.0,21.6,5.8,81.0,101.7,9.53
12,14,1,0,2003,1,1,0,1,0.016667,7278,...,3,6,38,21.6,0.0,21.6,5.8,81.0,101.7,9.53
13,13,0,0,2003,1,1,0,1,0.016667,21898,...,13,6,39,21.6,0.0,21.6,5.8,81.0,101.7,9.53
14,11,0,0,2003,1,1,0,0,0.000000,5950,...,7,13,62,21.6,0.0,21.6,5.8,81.0,101.7,9.53
15,20,0,0,2003,1,1,0,30,0.500000,1697,...,4,7,59,21.6,0.0,21.6,5.8,81.0,101.7,9.53
16,8,0,0,2003,1,1,0,0,0.000000,264,...,1,5,31,21.6,0.0,21.6,5.8,81.0,101.7,9.53
17,2,0,0,2003,1,1,0,0,0.000000,12335,...,6,8,49,21.6,0.0,21.6,5.8,81.0,101.7,9.53
18,19,0,0,2003,1,1,0,30,0.500000,14669,...,6,0,22,21.6,0.0,21.6,5.8,81.0,101.7,9.53
19,12,0,0,2003,1,1,0,0,0.000000,4482,...,1,10,74,21.6,0.0,21.6,5.8,81.0,101.7,9.53

In [4]:
# Scale the Data

#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()

columns = [col for col in crime if col not in ['c_id']] # 'type', 


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))

In [5]:
scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

,c_id,type,datetime,year,month,day,hour,minute,Hour_Minute,hundred_block,...,signal_200,trees_25,trees_100,rain_mm,snow_cm,total_precip_mm,temp_c,humidity,pressure,hours_of_light
0,16,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.084746,0.003475,0.021822,...,0.600000,0.212121,0.419847,0.235808,0.0,0.235808,0.408421,0.781609,0.612081,0.010909
1,10,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.318012,...,0.000000,0.424242,0.473282,0.235808,0.0,0.235808,0.408421,0.781609,0.612081,0.010909
2,15,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.016949,0.000695,0.221677,...,0.133333,0.242424,0.290076,0.235808,0.0,0.235808,0.408421,0.781609,0.612081,0.010909
3,18,1.0,0.000000,0.0,0.000000,0.000000,0.000000,0.338983,0.013899,0.122159,...,0.066667,0.242424,0.671756,0.235808,0.0,0.235808,0.408421,0.781609,0.612081,0.010909
4,5,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.995545,...,0.866667,0.181818,0.297710,0.235808,0.0,0.235808,0.408421,0.781609,0.612081,0.010909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552855,552408,0.0,0.999978,1.0,0.636364,0.933333,0.956522,0.322034,0.930507,0.144572,...,0.266667,0.272727,0.374046,0.000000,0.0,0.000000,0.711579,0.632184,0.577181,0.642424
552856,552411,0.0,0.999985,1.0,0.636364,0.933333,1.000000,0.966102,0.998610,0.432533,...,0.000000,0.090909,0.244275,0.000000,0.0,0.000000,0.692632,0.678161,0.578523,0.642424
552857,552410,0.0,0.999985,1.0,0.636364,0.933333,1.000000,0.118644,0.963864,0.065012,...,0.066667,0.242424,0.465649,0.000000,0.0,0.000000,0.692632,0.678161,0.578523,0.642424
552858,552412,0.0,0.999993,1.0,0.636364,0.966667,0.695652,0.813559,0.700486,0.880069,...,0.200000,0.151515,0.442748,0.000000,0.0,0.000000,0.751579,0.597701,0.605369,0.635152
552859,552413,0.0,1.000000,1.0,0.636364,0.966667,0.913043,0.644068,0.902015,0.892708,...,0.733333,0.272727,0.572519,0.000000,0.0,0.000000,0.682105,0.758621,0.597315,0.635152

In [6]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(387002, 30)

In [7]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

[0.05165755 0.02685996 0.02365015 0.03770431 0.04111126 0.03198457
 0.06114072 0.06541128 0.0168309  0.04811886 0.04959021 0.04910989
 0.04734961 0.01190917 0.02616672 0.03171994 0.04050006 0.00837816
 0.00634172 0.01004019 0.02105986 0.02798503 0.04487028 0.02142594
 0.00189856 0.02150001 0.04484998 0.03980594 0.04651009 0.04451907]
[ True False False  True  True False  True  True False  True  True  True
  True False False False  True False False False False False  True False
 False False  True  True  True  True]

In [8]:
feature_importances

                 importance
hundred_block      0.065411
Hour_Minute        0.061141
datetime           0.051658
utm_y              0.049590
latitude           0.049110
utm_x              0.048119
longitude          0.047350
pressure           0.046510
trees_100          0.044870
temp_c             0.044850
hours_of_light     0.044519
hour               0.041111
light_pole_100     0.040500
humidity           0.039806
day                0.037704
minute             0.031985
light_pole_50      0.031720
trees_25           0.027985
year               0.026860
light_pole_25      0.026167
month              0.023650
total_precip_mm    0.021500
rain_mm            0.021426
signal_200         0.021060
neighbourhood      0.016831
light_pole_12_5    0.011909
signal_100         0.010040
signal_25          0.008378
signal_50          0.006342
snow_cm            0.001899

In [9]:
## Import the random forest model.
from sklearn.ensemble import RandomForestClassifier 
## This line instantiates the model. 
rf = RandomForestClassifier() 
## Fit the model on your training data.
rf.fit(X_train, y_train) 
## And score it on your testing data.
rf.score(X_test, y_test)

feature_importances = pd.DataFrame(rf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

                 importance
hundred_block      0.063726
Hour_Minute        0.057532
datetime           0.051381
latitude           0.049458
longitude          0.047308
utm_y              0.047257
pressure           0.047162
utm_x              0.046436
temp_c             0.045238
trees_100          0.045108
hour               0.044720
hours_of_light     0.044454
humidity           0.040052
light_pole_100     0.039376
day                0.037298
light_pole_25      0.034207
minute             0.031866
light_pole_50      0.031497
trees_25           0.027672
year               0.026960
month              0.023853
total_precip_mm    0.022058
signal_200         0.021955
rain_mm            0.021155
neighbourhood      0.018158
light_pole_12_5    0.011300
signal_100         0.009360
signal_25          0.007543
signal_50          0.004030
snow_cm            0.001880

In [10]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [11]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[307100   6963]
 [ 62748  10191]]
              precision    recall  f1-score   support

         0.0       0.83      0.98      0.90    314063
         1.0       0.59      0.14      0.23     72939

    accuracy                           0.82    387002
   macro avg       0.71      0.56      0.56    387002
weighted avg       0.79      0.82      0.77    387002

In [13]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[131416   3232]
 [ 27093   4117]]
              precision    recall  f1-score   support

         0.0       0.83      0.98      0.90    134648
         1.0       0.56      0.13      0.21     31210

    accuracy                           0.82    165858
   macro avg       0.69      0.55      0.56    165858
weighted avg       0.78      0.82      0.77    165858

In [23]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=3000, 
                    learning_rate='adaptive', early_stopping=True)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [24]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[305060   9003]
 [ 61532  11407]]
              precision    recall  f1-score   support

         0.0       0.83      0.97      0.90    314063
         1.0       0.56      0.16      0.24     72939

    accuracy                           0.82    387002
   macro avg       0.70      0.56      0.57    387002
weighted avg       0.78      0.82      0.77    387002

In [25]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[130671   3977]
 [ 26481   4729]]
              precision    recall  f1-score   support

         0.0       0.83      0.97      0.90    134648
         1.0       0.54      0.15      0.24     31210

    accuracy                           0.82    165858
   macro avg       0.69      0.56      0.57    165858
weighted avg       0.78      0.82      0.77    165858

In [ ]:
# See how it changes with a MinMax Scaler (0 - 1)

# Results are the similar

In [ ]:
"""
crime = pd.read_csv('E:/Vancouver Crime Final/final_crime_fixed.csv')

### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))
crime['neighbourhood'] = le.fit_transform(crime['neighbourhood'].astype(str))

#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()

columns = [col for col in crime if col not in ['type', 'c_id']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))
"""

In [ ]:
"""
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)
"""

In [ ]:
"""
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())
"""

In [ ]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id', 'snow_cm', 'signal_25', 'signal_50', 'signal_100',
                                           'light_pole_12_5', 'neighbourhood', 'total_precip_mm', 'trees_25',
                                           'light_pole_25', 'hour', 'minute', 'latitude', 'longitude',
                                           'light_pole_50', 'Daytime', 'rain_mm', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

In [ ]:
X

In [ ]:
## Import the random forest model.
from sklearn.ensemble import RandomForestClassifier 
## This line instantiates the model. 
rf = RandomForestClassifier() 
## Fit the model on your training data.
rf.fit(X_train, y_train) 
## And score it on your testing data.
rf.score(X_test, y_test)

feature_importances = pd.DataFrame(rf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(11, 11, 11, 11), activation='relu', solver='adam', max_iter=5000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

In [ ]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))