In [12]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime_data = pd.read_csv('E:/University/Fall 2019/COMP 4480 - Directed Studies/Final Data/Partly Combined Data/Combined_data.csv')

In [13]:
crime_data

,vc_year,vc_month,vc_day,vc_hour,vc_minute,vc_hundred_block,vc_neighbourhood,vd_sunrise_hour,vd_sunrise_min,vd_sunset_hour,vd_sunset_min,vd_hours_of_sun,vwh_temp,vwh_visibility,vwh_weather,vwd_total_rain,vwd_total_snow,vwd_total_precip,vc_type
0,2003,1,6,4,30,1XX WATER ST,Central Business District,8,7,16,30,8.39,1.5,48.3,Clear,0.0,0.0,0.0,Mischief
1,2003,1,2,5,19,1XX ALEXANDER ST,Central Business District,8,8,16,26,8.30,7.4,9.7,"Moderate Rain,Fog",23.4,0.0,23.4,Theft from Vehicle
2,2003,1,2,5,13,OAK ST / SW MARINE DR,Marpole,8,8,16,26,8.30,7.4,9.7,"Moderate Rain,Fog",23.4,0.0,23.4,Vehicle Collision or Pedestrian Struck (with I...
3,2003,1,2,11,24,30XX LAUREL ST,Fairview,8,8,16,26,8.30,10.1,16.1,Cloudy,23.4,0.0,23.4,Break and Enter Residential/Other
4,2003,1,2,11,0,25XX MCBAIN AVE,Arbutus Ridge,8,8,16,26,8.30,10.1,16.1,Cloudy,23.4,0.0,23.4,Break and Enter Residential/Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551340,2019,8,27,17,0,28XX CAMBIE ST,Mount Pleasant,5,21,19,6,13.74,22.4,48.3,NaN,0.0,0.0,0.0,Theft from Vehicle
551341,2019,8,27,17,0,ALBERNI ST / BROUGHTON ST,West End,5,21,19,6,13.74,22.4,48.3,NaN,0.0,0.0,0.0,Theft from Vehicle
551342,2019,8,27,17,0,5XX HORNBY ST,Central Business District,5,21,19,6,13.74,22.4,48.3,NaN,0.0,0.0,0.0,Theft from Vehicle
551343,2019,8,28,1,7,10XX DUNSMUIR ST,Central Business District,5,23,19,4,13.68,16.4,32.2,Mainly Clear,0.0,0.0,0.0,Theft from Vehicle
551344,2019,8,28,1,6,28XX CAMBIE ST,Mount Pleasant,5,23,19,4,13.68,16.4,32.2,Mainly Clear,0.0,0.0,0.0,Break and Enter Residential/Other

In [14]:
# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime_data['vc_hundred_block'] = le.fit_transform(crime_data['vc_hundred_block'].astype(str))
crime_data['vc_neighbourhood'] = le.fit_transform(crime_data['vc_neighbourhood'].astype(str))
crime_data['vwh_weather'] = le.fit_transform(crime_data['vwh_weather'].astype(str))
crime_data['vc_type'] = le.fit_transform(crime_data['vc_type'])

# Display the results
crime_data

,vc_year,vc_month,vc_day,vc_hour,vc_minute,vc_hundred_block,vc_neighbourhood,vd_sunrise_hour,vd_sunrise_min,vd_sunset_hour,vd_sunset_min,vd_hours_of_sun,vwh_temp,vwh_visibility,vwh_weather,vwd_total_rain,vwd_total_snow,vwd_total_precip,vc_type
0,2003,1,6,4,30,3060,1,8,7,16,30,8.39,1.5,48.3,0,0.0,0.0,0.0,2
1,2003,1,2,5,19,2780,1,8,8,16,26,8.30,7.4,9.7,31,23.4,0.0,23.4,4
2,2003,1,2,5,13,18894,10,8,8,16,26,8.30,7.4,9.7,31,23.4,0.0,23.4,8
3,2003,1,2,11,24,6058,3,8,8,16,26,8.30,10.1,16.1,1,23.4,0.0,23.4,1
4,2003,1,2,11,0,4524,0,8,8,16,26,8.30,10.1,16.1,1,23.4,0.0,23.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551340,2019,8,27,17,0,5167,11,5,21,19,6,13.74,22.4,48.3,66,0.0,0.0,0.0,4
551341,2019,8,27,17,0,14406,22,5,21,19,6,13.74,22.4,48.3,66,0.0,0.0,0.0,4
551342,2019,8,27,17,0,10936,1,5,21,19,6,13.74,22.4,48.3,66,0.0,0.0,0.0,4
551343,2019,8,28,1,7,110,1,5,23,19,4,13.68,16.4,32.2,25,0.0,0.0,0.0,4
551344,2019,8,28,1,6,5167,11,5,23,19,4,13.68,16.4,32.2,25,0.0,0.0,0.0,1

In [15]:
crime_data.dtypes

vc_year               int64
vc_month              int64
vc_day                int64
vc_hour               int64
vc_minute             int64
vc_hundred_block      int32
vc_neighbourhood      int32
vd_sunrise_hour       int64
vd_sunrise_min        int64
vd_sunset_hour        int64
vd_sunset_min         int64
vd_hours_of_sun     float64
vwh_temp            float64
vwh_visibility      float64
vwh_weather           int32
vwd_total_rain      float64
vwd_total_snow      float64
vwd_total_precip    float64
vc_type               int32
dtype: object

In [25]:
# Encoding temperature to be above 0 for chi squared test
crime_data['vwh_temp'] = le.fit_transform(crime_data['vwh_temp'])

crime_data

,vc_year,vc_month,vc_day,vc_hour,vc_minute,vc_hundred_block,vc_neighbourhood,vd_sunrise_hour,vd_sunrise_min,vd_sunset_hour,vd_sunset_min,vd_hours_of_sun,vwh_temp,vwh_visibility,vwh_weather,vwd_total_rain,vwd_total_snow,vwd_total_precip,vc_type
0,2003,1,6,4,30,3060,1,8,7,16,30,8.39,126,48.3,0,0.0,0.0,0.0,2
1,2003,1,2,5,19,2780,1,8,8,16,26,8.30,185,9.7,31,23.4,0.0,23.4,4
2,2003,1,2,5,13,18894,10,8,8,16,26,8.30,185,9.7,31,23.4,0.0,23.4,8
3,2003,1,2,11,24,6058,3,8,8,16,26,8.30,212,16.1,1,23.4,0.0,23.4,1
4,2003,1,2,11,0,4524,0,8,8,16,26,8.30,212,16.1,1,23.4,0.0,23.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551340,2019,8,27,17,0,5167,11,5,21,19,6,13.74,335,48.3,66,0.0,0.0,0.0,4
551341,2019,8,27,17,0,14406,22,5,21,19,6,13.74,335,48.3,66,0.0,0.0,0.0,4
551342,2019,8,27,17,0,10936,1,5,21,19,6,13.74,335,48.3,66,0.0,0.0,0.0,4
551343,2019,8,28,1,7,110,1,5,23,19,4,13.68,275,32.2,25,0.0,0.0,0.0,4
551344,2019,8,28,1,6,5167,11,5,23,19,4,13.68,275,32.2,25,0.0,0.0,0.0,1

In [26]:
# split for training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime_data if col not in ['vc_type']]

X = crime_data[cols]

# Select target data
y = crime_data['vc_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(385941, 18)

In [27]:
# Tutorial via https://towardsdatascience.com/feature-selection-using-python-for-classification-problem-b5f00a1c7028

# Check for zero variance features
from sklearn.feature_selection import VarianceThreshold

sel_variance_threshold = VarianceThreshold() 
X_train_remove_variance = sel_variance_threshold.fit_transform(X_train)
print(X_train_remove_variance.shape)

(385941, 18)

In [28]:
# Use a chi squared test to test relationship between each feature and the target

from sklearn.feature_selection import SelectKBest, chi2

sel_chi2 = SelectKBest(chi2, k=4)    # select 4 features
X_train_chi2 = sel_chi2.fit_transform(X_train, y_train)
print(sel_chi2.get_support())

[False False False False  True  True False False False False False False
  True False  True False False False]

Chi2: 4 Best True Columns: vc_minute, vc_hundred_block, vwh_temp, vwh_weather

In [29]:
# try f test
from sklearn.feature_selection import SelectKBest, f_classif

sel_f = SelectKBest(f_classif, k=4)
X_train_f = sel_f.fit_transform(X_train, y_train)
print(sel_f.get_support())

[ True False False  True  True  True False False False False False False
 False False False False False False]

f test: 4 Best True Columns: vc_year, vc_minute, vc_hundred_block, vc_neighbourhood,

In [31]:
# mutual_info_classif test
from sklearn.feature_selection import mutual_info_classif

sel_mutual = SelectKBest(mutual_info_classif, k=4)
X_train_mutual = sel_mutual.fit_transform(X_train, y_train)
print(sel_mutual.get_support())

[False False False  True  True  True  True False False False False False
 False False False False False False]

mutual_info_classif: 4 Best True Columns: vc_hour, vc_minute, vc_hundred_block, vc_neighbourhood

But all the above are when we have 8 target options.  Lets simplify it to 2

In [52]:
# Encode all Break and Enter's as 1 and everything else as 2

crime_simple_type = pd.read_csv('E:/University/Fall 2019/COMP 4480 - Directed Studies/Final Data/Partly Combined Data/Combined_data.csv')

crime_simple_type = crime_simple_type.replace(['Mischief', 'Theft from Vehicle',
       'Vehicle Collision or Pedestrian Struck (with Injury)',
       'Theft of Vehicle', 'Theft of Bicycle', 'Other Theft',
       'Vehicle Collision or Pedestrian Struck (with Fatality)'], 0)

crime_simple_type = crime_simple_type.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)

# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime_simple_type['vc_hundred_block'] = le.fit_transform(crime_simple_type['vc_hundred_block'].astype(str))
crime_simple_type['vc_neighbourhood'] = le.fit_transform(crime_simple_type['vc_neighbourhood'].astype(str))
crime_simple_type['vwh_weather'] = le.fit_transform(crime_simple_type['vwh_weather'].astype(str))

# Encoding temperature to be above 0 for chi squared test
crime_simple_type['vwh_temp'] = le.fit_transform(crime_simple_type['vwh_temp'])

crime_simple_type

,vc_year,vc_month,vc_day,vc_hour,vc_minute,vc_hundred_block,vc_neighbourhood,vd_sunrise_hour,vd_sunrise_min,vd_sunset_hour,vd_sunset_min,vd_hours_of_sun,vwh_temp,vwh_visibility,vwh_weather,vwd_total_rain,vwd_total_snow,vwd_total_precip,vc_type
0,2003,1,6,4,30,3060,1,8,7,16,30,8.39,126,48.3,0,0.0,0.0,0.0,0
1,2003,1,2,5,19,2780,1,8,8,16,26,8.30,185,9.7,31,23.4,0.0,23.4,0
2,2003,1,2,5,13,18894,10,8,8,16,26,8.30,185,9.7,31,23.4,0.0,23.4,0
3,2003,1,2,11,24,6058,3,8,8,16,26,8.30,212,16.1,1,23.4,0.0,23.4,1
4,2003,1,2,11,0,4524,0,8,8,16,26,8.30,212,16.1,1,23.4,0.0,23.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551340,2019,8,27,17,0,5167,11,5,21,19,6,13.74,335,48.3,66,0.0,0.0,0.0,0
551341,2019,8,27,17,0,14406,22,5,21,19,6,13.74,335,48.3,66,0.0,0.0,0.0,0
551342,2019,8,27,17,0,10936,1,5,21,19,6,13.74,335,48.3,66,0.0,0.0,0.0,0
551343,2019,8,28,1,7,110,1,5,23,19,4,13.68,275,32.2,25,0.0,0.0,0.0,0
551344,2019,8,28,1,6,5167,11,5,23,19,4,13.68,275,32.2,25,0.0,0.0,0.0,1

Now, test again

In [53]:
# split for training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime_simple_type if col not in ['vc_type']]

X = crime_simple_type[cols]

# Select target data
y = crime_simple_type['vc_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(385941, 18)

In [54]:
# Check for zero variance features
from sklearn.feature_selection import VarianceThreshold

sel_variance_threshold = VarianceThreshold() 
X_train_remove_variance = sel_variance_threshold.fit_transform(X_train)
print(X_train_remove_variance.shape)

(385941, 18)

In [55]:
crime_simple_type['vwh_temp'].unique()

array([126, 185, 212, 207, 198, 170, 118, 166, 139, 184, 140, 190, 224,
       220, 202, 148, 223, 177, 200, 153, 213, 234, 186, 187, 209, 204,
       226, 230, 225, 277, 221, 264, 245, 244, 273, 250, 217, 295, 243,
       278, 232, 231, 253, 292, 286, 327, 281, 258, 380, 357, 335, 309,
       272, 304, 262, 276, 269, 299, 307, 284, 233, 210, 219, 270, 229,
       183, 119, 163, 162, 151, 192, 133, 168, 149, 142, 101,  58,  25,
        12,  57, 181, 199, 180, 155, 189, 144, 152, 176, 143, 160, 214,
       215, 175, 169, 193, 138, 206, 239, 237, 290, 294, 320, 312, 251,
       255, 259, 249, 247, 275, 261, 257, 333, 297, 343, 326, 293, 328,
       287, 331, 305, 346, 300, 342, 268, 263, 282, 218, 260, 254, 194,
       227, 197, 188, 173, 167, 104,  28, 150, 164, 191, 195, 147, 174,
       116, 109, 145, 196, 172, 178, 201, 222, 246, 289, 242, 298, 238,
       283, 279, 313, 252, 319, 288, 291, 211, 128, 165, 159, 117,  99,
       236, 179, 137, 156, 182, 131, 265, 266, 256, 271, 311, 318, 385,
       347, 356, 355, 241,  97, 121, 135, 161,  46, 114, 125, 157, 141,
       228, 248, 317, 341, 348, 315, 349, 274, 280, 216, 132, 158, 103,
        89, 129, 154, 205, 285, 354, 323, 337, 338,  95, 171, 136, 124,
        67, 122, 120,  81,  92, 330, 334, 296, 322, 378, 361, 352, 321,
       203, 130, 208, 235, 324, 375, 332, 336, 339, 329,  91, 107, 112,
       123, 303, 302, 301, 146, 267, 340, 310, 325,  75, 111, 108, 240,
       306,  38, 105,  68, 127, 362, 350,  76,  90,  74, 134, 314, 113,
       115,  39,  64,  56, 316, 308,  98,  84,  96,  72,  79,  86, 360,
       106, 365, 370, 376, 367, 372, 359, 344,  27,  93, 363, 366,  66,
        59,  49,  42, 408, 100, 364, 345,  73,  65,  15,  80,  71,  69,
        53,  88, 353, 102, 399, 110,  30, 393,  47,  61,  51,  63, 383,
       351, 377,  54,  82,  94,  70, 368, 384,  52, 373,  77,  50,  55,
        43, 389,  85, 405, 404,  78, 410, 358,  45,  21, 386,  87,  37,
        40,  60, 417, 371,  83,  22,  48, 379, 387, 381,  13,  34,  62,
       369,  35, 396,  32, 374,  20,  31, 382,  41, 414, 392, 395, 398,
        16, 416, 403,  33,  44,  26,  18, 390,  29, 412,  17, 415,  36,
       394,   4,  19, 419, 420,   2, 388,   6, 409,   9, 391,   3,  24,
       411, 402,   0, 407, 397,  11,   8,  10, 413, 406,   7,  14, 400,
       418, 401,  23,   5,   1], dtype=int64)

In [56]:
# Use a chi squared test to test relationship between each feature and the target

from sklearn.feature_selection import SelectKBest, chi2

sel_chi2 = SelectKBest(chi2, k=4)    # select 4 features
X_train_chi2 = sel_chi2.fit_transform(X_train, y_train)
print(sel_chi2.get_support())

[False False False  True False  True False False False False False False
  True False  True False False False]

Chi2: 4 Best True Columns: vc_hour, vc_hundred_block, vwh_temp, vwh_weather

Same as 8 Target Values

In [57]:
# try f test
from sklearn.feature_selection import SelectKBest, f_classif

sel_f = SelectKBest(f_classif, k=4)
X_train_f = sel_f.fit_transform(X_train, y_train)
print(sel_f.get_support())

[ True False False  True False  True False False False False False False
  True False False False False False]

Different from 8 options!

f test: 4 Best True Columns: vc_year, vc_hour, vc_hundred_block, vwh_temp

In [58]:
# mutual_info_classif test
from sklearn.feature_selection import mutual_info_classif

sel_mutual = SelectKBest(mutual_info_classif, k=4)
X_train_mutual = sel_mutual.fit_transform(X_train, y_train)
print(sel_mutual.get_support())

[False False False  True False  True  True False False False False False
 False  True False False False False]

Different from 8 options!

mutual_info_classif: 4 Best True Columns: vc_hour, vc_hundred_block, vc_neighbourhood, vwh_visibility

In [61]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

[0.0515783  0.01842449 0.05878366 0.08988167 0.06468419 0.18067731
 0.09048296 0.01019456 0.05872812 0.01059128 0.05993623 0.06906258
 0.09997572 0.03389316 0.03626746 0.03222209 0.00213659 0.03247965]
[False False  True  True  True  True  True False  True False  True  True
  True False False False False False]

Random Forest Classifier likes:
    
    vc_day, vc_hour, vc_minute, vc_hundred_block, vc_neighbourhood, vd_sunrise_min, vd_sunset_min, vd_hours_of_sun, vwh_temp